### PR TITLE
update gradle and add java 10 base image

### PR DESCRIPTION
**Pull request by varpa89**

### CODE REVIEW

**Comment by HaVonTe1** [comment]
+1
Thx a lot.

**Comment by bjornmagnusson** [comment]
Please remove the gradle upgrade from the PR, and rebase your branch.
Gradle upgrades affects too much to be in a feature PR. 
Merged a fix for https://blog.gradle.org/unable-to-download-maven-central-bintray in #140.

**Comment by varpa89** [comment]
Ok! I'll do another clean PR.

**Comment by varpa89** [comment]
here is https://github.com/Transmode/gradle-docker/pull/141

**Pull request closed without merging**
