### PR TITLE
Add multiple tags

### PR DESCRIPTION
**Pull request by jcfandino**
Addressed enhancement #50 
Added support for multiple tags.

### CODE REVIEW

**Comment by jcfandino** [comment]
Please see this comment: https://github.com/Transmode/gradle-docker/issues/50#issuecomment-323040003
about travis error.

**Comment by bjornmagnusson** [comment]
The PR does a bit too much.
Please do not upgrade Gradle.
Also, why the upgrade of docker-java library?

**Comment by jcfandino** [comment]
Thanks for your feedback.
I reverted the gradle change.
The previous version of docker-java doesn't support multiple tags, in was introduced in 3.0.10: https://github.com/docker-java/docker-java/milestone/20?closed=1

The travis error seems unrelated to the PR, it builds fine if I set it to use openjdk8 instead of openjdk7, I think the same error will happen in master.

**Comment by maximbaz** [comment]
Hey @bjornmagnusson, is there anything else needed from your point of view to get this merged? This would be a neat addition when a new version is eventually released #105.

**Pull request closed without merging**
